const notes = [
    {id: 1, title: 'How to Create Stunning Graphics', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non libero a arcu fermentum vehicula. Phasellus bibendum consectetur tristique. Sed eget nunc nec justo finibus convallis id nec arcu. Vivamus non nunc a purus consectetur scelerisque.' , date: 'Oct 1, 2023'},
    {id: 2, title: 'Effective Time Management Techniques', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam in placerat purus. Nunc in quam ut odio varius fringilla. Nullam vel massa a elit eleifend dictum nec nec elit. Duis ac efficitur libero. Nulla facilisi.' , date: 'Oct 2, 2023'},
    {id: 3, title: 'Mastering JavaScript Programming', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget urna vel justo blandit luctus. Cras eleifend augue id metus scelerisque, non auctor orci laoreet. In vehicula arcu id erat feugiat' , date: 'Oct 3, 2023'},
    {id: 4, title: 'Cooking Delicious Italian Cuisine', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Sed eu velit vel orci facilisis sollicitudin. Fusce euismod augue in mi auctor, at dapibus augue eleifend. Fusce in efficitur velit.' , date: 'Oct 4, 2023'},
    {id: 5, title: 'Exploring Beautiful Natural Parks', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean a eros at mi cursus lacinia in a justo. Suspendisse potenti. Proin bibendum laoreet sapien, in placerat risus fermentum id.' , date: 'Oct 5, 2023'},
    {id: 6, title: 'Digital Marketing Strategies', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus dapibus lectus ut orci vehicula, id viverra augue posuere. Sed bibendum lectus a erat bibendum, non vehicula nunc vulputate.' , date: 'Oct 6, 2023'},
    {id: 7, title: 'Hiking Adventures in the Mountains', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque luctus justo vel justo facilisis, sit amet efficitur quam bibendum. Suspendisse id enim vitae ex rutrum tincidunt.' , date: 'Oct 7, 2023'},
    {id: 8, title: 'Photography Tips for Beginners', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod massa ut tellus fringilla, eget laoreet purus mattis. Nam nec diam in tellus scelerisque elementum ac sit amet libero.' , date: 'Oct 8, 2023'},
    {id: 9, title: 'Healthy Lifestyle and Nutrition', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultrices justo vel lectus ultricies, in egestas arcu consectetur. Aliquam id justo id nulla viverra commodo.' , date: 'Oct 9, 2023'},
    {id: 10, title: 'Traveling the World on a Budget', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec justo ut ex condimentum tempus. Nulla facilisi. Curabitur eget ligula in mi auctor scelerisque a eu arcu.' , date: 'Oct 10, 2023'},
];

export default notes;
